import type { Metadata } from "next"
import localFont from "next/font/local"

import "./globals.css"

import { FormProvider } from "@/lib/hooks/use-form"
import Layout from "@/components/layout"

import QueryProvider from "./providers/query-provider"

const montserrat = localFont({
  src: "./fonts/Montserrat.ttf",
  variable: "--font-montserrat",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <QueryProvider>
          <FormProvider>
            <Layout>{children}</Layout>
          </FormProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
