FROM node:22 as build

WORKDIR /app

COPY ./Frontend/package*.json ./

RUN npm install --include=dev

COPY ./Frontend .
RUN npm run build
ENV NODE_ENV=production
ENV NEXT_PUBLIC_BASE_URL=http://localhost:8000

EXPOSE 80
EXPOSE 443

CMD ["npm", "start"]